export const shopCategories = [
  { value: "art", label: "Art & Craft Supplies" },
  { value: "music", label: "Musical Instruments & Accessories" },
  { value: "technology", label: "Software & Technology Services" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home_decor", label: "Home Decor & Furniture" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys, Kids & Baby Products" },
  { value: "sports", label: "Sports & Outdoor Equipment" },
  { value: "food", label: "Food, Beverages & Gourmet" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "automotive", label: "Automotive Parts & Accessories" },
  { value: "health", label: "Health & Wellness" },
  { value: "gardening", label: "Gardening & Plants" },
  { value: "handmade", label: "Handmade & Custom Products" },
  { value: "office_supplies", label: "Office & Business Supplies" },
  { value: "footwear", label: "Shoes & Footwear" },
  { value: "gaming", label: "Gaming & Esports Accessories" },
  { value: "digital_services", label: "Digital Products & Online Services" },
  { value: "photography", label: "Photography & Videography Gear" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "hardware", label: "Tools, Hardware & Industrial Supplies" },
];
